### PR TITLE
Database upgrades and models

### PR DESCRIPTION
**Pull request by alaski**
There is cleanup necessary here.  But this is enough to get alembic to autogenerate migrations and attempt upgrades.

### CODE REVIEW

**Comment by jaypipes** [comment]
I'd like to streamline the model and schema a bit before accepting this first migration... let's chat about this later this week or early next week.

**Comment by alaski** [comment]
Sure.  I'm about halfway through getting functional tests running at the moment so I still have a bit to do, but it would be good to get your thoughts on the db models.  I was planning to add a Text field to hold the API params but otherwise don't have any modifications already in mind.

**Comment by alaski** [comment]
This has grown to a fairly large change.  In gerrit I would split this out but it's a bit more troublesome to do in github.  I can do so if requested though.

**Comment by cdent** [comment]
The infrastructure looks fine, the only questions I have surround the database models.

* Are they a proposed end-state for what we'd have or something to fill in the blank for now?
* I was kind of hoping/assuming there would be some way we could directly use [taskflow's persistence](http://docs.openstack.org/developer/taskflow/persistence.html) and flow modelling as our logic layer under the API but I'm making that statement from a complete position of ignorance. I don't actually know if that's possible.

I'm cool with merging this and evolving the model as we see fit. It's actually doing anything yet, so as long as we can change our minds...

**Comment by alaski** [comment]
The database models are my proposed end-state though Jay indicated that he would like to see them streamlined. I need to catch him to clarify what that means.

I think we will use taskflows persistence and flow modelling but I don't think we want to expose that to API users. The Task and TaskItem will be the user visible abstractions on top of what taskflow provides. At least that's the plan I've been working off of. If we want to go the route of using taskflow modelling and persistence right up front we'll need a translation layer to convert whatever that looks like into something easily consumable for API users.

Yeah, the benefit of having no users yet is that we can totally scratch this and move in a different direction if we want to later.

**Pull request merged**
